### ISSUE TITLE
build-harness gh actions doesn't work with act

### ISSUE THREAD

**Issue by 3h4x** [cloudposse/build-harness#235]
`act` should work with our `gh actions` in this repo. 
It would simplify workflow and allow to test changes before pushing.
Especially this flag is interesting for continuous testing ` --watch - watch the contents of the local repo and run when files change`

```
act             
[cloudposse-terraform-workflow/pre-commit] 🚀  Start image=node:12.6-buster-slim
[lint/readme                             ] 🚀  Start image=node:12.6-buster-slim
[cloudposse-terraform-workflow/pre-commit]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[lint/readme                             ]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[cloudposse-terraform-workflow/pre-commit]   🐳  docker cp src=/workspace/cloudposse.terraform-opsgenie/. dst=/github/workspace
[lint/readme                             ]   🐳  docker cp src=/workspace/cloudposse.terraform-opsgenie/. dst=/github/workspace
[lint/readme                             ] ⭐  Run actions/checkout@master
[lint/readme                             ]   ✅  Success - actions/checkout@master
[lint/readme                             ] ⭐  Run cloudposse/build-harness@0.39.0
[lint/readme                             ]   ☁  git clone 'https://github.com/cloudposse/build-harness' # ref=0.39.0
[cloudposse-terraform-workflow/pre-commit] ⭐  Run actions/checkout@v1
[cloudposse-terraform-workflow/pre-commit]   ✅  Success - actions/checkout@v1
[cloudposse-terraform-workflow/pre-commit] ⭐  Run actions/setup-python@v1
[cloudposse-terraform-workflow/pre-commit]   ☁  git clone 'https://github.com/actions/setup-python' # ref=v1
[lint/readme                             ]   ❌  Failure - cloudposse/build-harness@0.39.0
Error: open /.cache/act/cloudposse-build-harness@0.39.0/action.yaml: no such file or directory
```

Sample `action.yaml` from `actions-setup-python@v1` repo:
```
---
name: 'Setup Python'
description: 'Set up a specific version of Python and add the command-line tools to the PATH.'
author: 'GitHub'
inputs:
  python-version:
    description: "Version range or exact version of a Python version to use, using SemVer's version range syntax."
    default: '3.x'
  architecture:
    description: 'The target architecture (x86, x64) of the Python interpreter.'
    default: 'x64'
outputs:
  python-version:
    description: "The installed python version. Useful when given a version range as input."
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'yellow'
```
